version: '3.8'

services:
  hiddify:
    image: ghcr.io/hiddify/hiddify-core:latest
    network_mode: host
    volumes:
      - ./hiddify.json:/hiddify/hiddify.json
    command: ["/opt/hiddify.sh"]
